openapi: 3.2.0
info:
  title: Switchfly Loyalty Shopping Flow API
  description: Switchfly uses **OAuth 2** for the SSO authentication required to communicate with any 3rd party API in order to perform loyalty account actions.
  version: v3.4
tags:
- name: Shopping Flow
  description: Information about requests performed by Switchfly system to 3rd party service to fetch Loyalty profile data and redeem points from the customer account.
paths:
  /traveler-profile:
    get:
      tags:
      - Shopping Flow
      summary: Retrieve Traveler Profile information
      description: 'Request performed to 3rd party endpoint to fetch Traveler Profile information such as `travelerProfileId`, `firstName`, `balancePoints`, `customerCurrency`

        - Supported Currencies:

        - USD

        - AED

        - AUD

        - BBD

        - BRL

        - BSD

        - CAD

        - COP

        - CRC

        - DOP

        - EUR

        - GBP

        - GTQ

        - HNL

        - IDR

        - ILS

        - INR

        - JMD

        - JOD

        - JPY

        - MXN

        - MYR

        - NOK

        - NZD

        - PAB

        - PEN

        - PHP

        - PLN

        - SGD

        - THB

        - TTD

        - UYU

        - VND

        - XCD

        - ZAR


        - Supported Languages:

        - English

        - French

        - Spanish

        - LA Spanish

        - Chinese_Simplified

        - Japanese

        - BR Portuguese

        - Thai

        - German'
      operationId: TravelerProfile
      security:
      - bearerAuth: []
      parameters:
      - in: header
        name: UserToken
        description: Unique string token used to identify user session in case `client_credential` grant type was used for OAuth 2 SSO.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TravelerProfile'
              examples:
                TravelerProfile:
                  $ref: '#/components/examples/TravelerProfile'
  /redeem:
    post:
      tags:
      - Shopping Flow
      summary: Redeem points from Traveler Points account
      description: 'This API will allow Switchfly the capability of redeeming points from a customer loyalty profile account.


        Switchfly will send a request to this API endpoint using a JSON payload which will describe the products the customer (booking components) is redeeming points on.


        This will include the points and cash used for each component and will also include information whether or not a credit card payment top up was needed to complete the booking.


        The only requirement for this endpoint is to return Switchfly a unique transaction id that represents the redemption transaction for this customer `redemptionConfirmationId`


        This is important since this `redemptionConfirmationId` will be used by Switchfly if a points refund request is needed later to cancel a booking or individual components of it.


        **Note:**


        If a failure occurs after the redeem call is executed, the auto-cancel process will be activated to prevent the user from losing any points. Switchfly will then initiate a product cancellation and initiate a refund, as outlined in the following chart:


        User


        User


        Switchfly


        Switchfly


        3rd party

        Authorization service


        3rd party...


        3rd party

        Redemption API


        3rd party...


        Redemption RQ + access_token


        Redemption RQ + access_token


        Redemption Confirmation RS


        Redemption Confirmation RS


        Checkout Redeem Product


        Checkout Redeem Product


        Refund RQ + access token


        Refund RQ + access token


        Refund RS


        Refund RS


        Refund autocancel


        Refund autocancel


        1


        1


        2


        2


        8


        8


        9


        9


        Traveler Profile RQ + access_token


        Traveler Profile RQ + access_token


        Traveler Profile RS


        Traveler Profile RS


        6


        6


        Traveler Profile RQ + access_token


        Traveler Profile RQ + access_token


        Traveler Profile RS


        Traveler Profile RS


        4


        4


        3


        3


        5


        5


        7


        7


        10


        10


        Client credentials Grant RQ


        client_id


        secret


        Client credentials Grant RQ...


        Client credentials Acces token RS


        Client credentials Acces token RS


        9


        9


        10


        10Text is not SVG - cannot display'
      operationId: Redeem
      security:
      - bearerAuth: []
      parameters:
      - in: header
        name: UserToken
        description: Unique string token used to identify user session in case `client_credential` grant type was used for SSO.
        required: false
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Redeem'
            examples:
              RedeemAirPoints:
                $ref: '#/components/examples/RedeemAirFullPoints'
              RedeemAirRoomActivityCarPointsCash:
                $ref: '#/components/examples/RedeemAirRoomActivityCarPointsAndCash'
              RedeemActivityCarMixedPointsAndCash:
                $ref: '#/components/examples/RedeemActivityCarMixedPointsAndCash'
              RedeemRoomCarNoPoints:
                $ref: '#/components/examples/RedeemRoomCarNoPoints'
              RedeemAirRoomInsurancePointsCash:
                $ref: '#/components/examples/RedeemAirRoomInsurancePointsCash'
              RedeemActivityCash:
                $ref: '#/components/examples/RedeemActivityCash'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedemptionConfirmation'
        '400':
          description: Malformed request
        '401':
          description: Not authorized to access the resource
        '403':
          description: It is forbidden to access the channel
        default:
          description: Unexpected Error
components:
  examples:
    RedeemAirRoomActivityCarPointsAndCash:
      value:
        bookingId: '1234567'
        createdDate: 2023-07-0718:54:00Z
        travelerProfileId: uniqueId1234
        points: 68450
        customerCurrency: USD
        lang: 1
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        addressLine2: More address details
        city: Denver
        state: Colorado
        postalCode: '80249'
        emailSubscription: false
        metadata:
          payments:
          - type: Credit Card
            amount: 100
            currency: USD
            pointsAmount: 10000
          products:
          - id: 1
            type: AIR
            description: (JFK - CLT - SFO) - (SFO - JFK)
            pointsAmount: 48300
            shortfallCash: 0
            fullPrice: 483
            costOfGoods: 420
            tax: 17.7
            attributes:
              recordLocator: '12345'
              isRoundTrip: true
              travelerCounts:
                adults: 2
                children: 1
                infantsInSeat: 1
                infantsInLap: 0
              legs:
              - departureAirportCode: JFK
                departureDate: 2023-09-18 05:30
                arrivalAirportCode: SFO
                arrivalDate: 2023-09-18 11:45
                flightNumbers:
                - '1111'
                - '4567'
                airlineCodes:
                - AA
                layoverAirportCodes:
                - CLT
              - departureAirportCode: SFO
                departureDate: 2023-09-21 12:30
                arrivalAirportCode: JFK
                arrivalDate: 2023-09-21 17:45
                flightNumbers:
                - '555'
                airlineCodes:
                - AA
                layoverAirportCodes: []
          - id: 2
            type: ROOM
            description: Doubletree Hotel San Francisco Airport
            pointsAmount: 12000
            shortfallCash: 0
            fullPrice: 120
            costOfGoods: 104.34
            tax: 4.39
            attributes:
              hotelName: Doubletree Hotel San Francisco Airport
              hotelCity: BURLINGAME
              hotelCountry: US
              roomDescription: Room description
              checkIn: 2023-09-18 10:30
              checkOut: 2023-09-21 10:30
              nights: 2
              roomType: room_type
              occupantsCount: 1
          - id: 3
            type: ACTIVITY
            description: Swim with dolphins
            pointsAmount: 8150
            shortfallCash: 0
            fullPrice: 81.5
            costOfGoods: 70.86
            tax: 2.98
            attributes:
              activityName: Swim with dolphins
              activityDescription: Short description
              scheduledDate: 2023-09-19 10:00
              airportCode: SFO
              tourDuration: tour_duration
              description: Short description
          - id: 4
            type: CAR
            description: Toyota Trueno
            pointsAmount: 0
            shortfallCash: 100
            fullPrice: 100
            tax: 3.58
            attributes:
              companyName: Enterprise
              carDescription: Sipp Description
              mileage: Unlimited
              pickUpDate: 2023-09-18 16:00
              pickupLocation: SFO Airport
              dropOffDate: 2023-09-21 10:00
              dropOffLocation: SFO Airport
    RedeemActivityCash:
      value:
        bookingId: '1234567'
        points: 0
        type: travel
        customerCurrency: USD
        lang: 1
        createdDate: 2025-06-26 03:59
        travelerProfileId: checkout@test.com
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        city: Denver
        state: Colorado
        postalCode: '80249'
        emailSubscription: false
        metadata:
          payments:
          - type: Credit Card
            amount: 48.65
            currency: USD
            pointsAmount: 0
          products:
          - id: 1121
            type: ACTIVITY
            description: California Sunset Cruise (2-hours)
            pointsAmount: 0
            fullPrice: 48.65
            shortfallCash: 0
            attributes:
              activityName: California Sunset Cruise (2-hours)
              activityDescription: Experience the magic of San Francisco ...
              scheduledDate: 2025-08-13 19:00
              airportCode: SFO
              tourDuration: 2 hours
              description: 'Experience the magic of San Francisco ... '
    RedeemActivityCarMixedPointsAndCash:
      value:
        bookingId: '1234567'
        createdDate: 2023-07-0718:54:00Z
        travelerProfileId: uniqueId1234
        points: 10150
        customerCurrency: USD
        lang: 1
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        addressLine2: More address details
        city: Denver
        state: Colorado
        postalCode: '80249'
        emailSubscription: true
        metadata:
          payments:
          - type: Credit Card
            amount: 80
            currency: USD
            pointsAmount: 8000
          products:
          - id: 11
            type: ACTIVITY
            description: Swim with dolphins
            pointsAmount: 8150
            shortfallCash: 0
            fullPrice: 81.5
            costOfGoods: 70.86
            tax: 2.98
            attributes:
              activityName: Swim with dolphins
              activityDescription: Short description
              scheduledDate: 2023-09-19 10:00
              airportCode: SFO
              tourDuration: tour_duration
              description: Short description
          - id: 11
            type: CAR
            description: Toyota Trueno
            pointsAmount: 2000
            shortfallCash: 80
            fullPrice: 100
            tax: 3.58
            attributes:
              companyName: Enterprise
              carDescription: Sipp Description
              mileage: Unlimited
              pickUpDate: 2023-09-18 16:00
              pickupLocation: SFO Airport
              dropOffDate: 2023-09-21 10:00
              dropOffLocation: SFO Airport
    RedeemAirFullPoints:
      value:
        bookingId: '1234567'
        createdDate: 2023-07-0718:54:00Z
        travelerProfileId: uniqueId1234
        points: 48300
        customerCurrency: USD
        lang: 1
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        addressLine2: More address details
        city: Denver
        state: Colorado
        postalCode: '80249'
        emailSubscription: true
        metadata:
          payments: []
          products:
          - id: 1
            type: AIR
            description: (JFK - CLT - SFO) - (SFO - JFK)
            pointsAmount: 48300
            shortfallCash: 0
            fullPrice: 483
            costOfGoods: 420
            tax: 17.7
            attributes:
              recordLocator: '12345'
              isRoundTrip: true
              travelerCounts:
                adults: 2
                children: 1
                infantsInSeat: 1
                infantsInLap: 0
              legs:
              - departureAirportCode: JFK
                departureDate: 2023-09-18 05:30
                arrivalAirportCode: SFO
                arrivalDate: 2023-09-18 11:45
                flightNumbers:
                - '1111'
                - '4567'
                airlineCodes:
                - AA
                layoverAirportCodes:
                - CLT
              - departureAirportCode: SFO
                departureDate: 2023-09-21 12:30
                arrivalAirportCode: JFK
                arrivalDate: 2023-09-21 17:45
                flightNumbers:
                - '555'
                airlineCodes:
                - AA
                layoverAirportCodes: []
          - id: 2
            type: FEE
            description: Standalone Air Booking Fee
            pointsAmount: 2000
            shortfallCash: 0
            fullPrice: 20
            costOfGoods: 0
            tax: 0
            attributes:
              contractName: Standalone Air Booking Fee
              feeType: BOOKING
    TravelerProfile:
      value:
        travelerProfileId: uniqueTravelerId
        balancePoints: 150000
        title: Mr
        firstName: firstName
        lastName: lastName
        email: test@switchfly.com
        phone: '7204909090'
        customerCurrency: USD
        langId: 1
        companyCode: PointBank1234
        address:
          addressLine1: 12 Grimmauld Place
          city: Long Beach
          countryCode: US
          state: CA
          postalCode: '123456'
    RedeemRoomCarNoPoints:
      value:
        bookingId: '1234567'
        createdDate: 2023-07-0718:54:00Z
        travelerProfileId: uniqueId1234
        points: 0
        customerCurrency: USD
        lang: 1
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        addressLine2: More address details
        city: Denver
        state: Colorado
        postalCode: '80249'
        emailSubscription: true
        metadata:
          payments:
          - type: Credit Card
            amount: 152.96
            currency: USD
            pointsAmount: 0
          products:
          - id: 43
            type: ROOM
            description: Holiday Inn Miami West - Airport Area, an IHG Hotel
            pointsAmount: 0
            fullPrice: 119.52
            costOfGoods: 98.06
            tax: 12.24
            shortfallCash: 0
            attributes:
              hotelName: Holiday Inn Miami West - Airport Area, an IHG Hotel
              hotelCity: Hialeah
              hotelCountry: US
              roomDescription: 'Bedding requests cannot be guaranteed. Please contact the property to confirm.

                <p><strong>1 King Bed and 1 Double Sofa Bed</strong></p><p>190-sq-foot room with city views </p><br/><p><b>Layout</b> - Separate sitting area</p><p><b>Internet</b> - Free WiFi </p><p><b>Entertainment</b> - Premium channels </p><p><b>Food & Drink</b> - Refrigerator, coffee/tea maker,  room service (limited hours), and microwave (on request)</p><p><b>Sleep</b> - A pillow menu, blackout drapes/curtains, and bed sheets </p><p><b>Bathroom</b> - Private bathroom, shower/tub combination, bathrobes, and free toiletries</p><p><b>Practical</b> - Sofa bed, free local calls, and laptop-compatible safe</p><p><b>Comfort</b> - Fresh bed sheets (on request), fresh towels (on request), and climate-controlled air conditioning</p><p><b>Accessibility</b> - Thin carpet in room</p><p><b>Eco-friendly</b> - Eco-friendly toiletries, eco-friendly cleaning supplies, energy-saving switches, and recycling bin</p><p><b>Need to Know</b> - Weekly housekeeping</p><p>Non-Smoking</p><p>Room/bed type depends on availability at check-in </p>'
              checkIn: 2024-07-03 16:00
              checkOut: 2024-07-04 11:00
              nights: 1
              roomType: Standard Room, 1 King Bed with Sofa bed - 1 King Bed, 1 Sofa Bed
              occupantsCount: 1
          - id: 29
            type: CAR
            description: Nissan Versa or similar
            pointsAmount: 0
            fullPrice: 33.44
            costOfGoods: 27.87
            tax: 0
            shortfallCash: 0
            attributes:
              companyName: MEX
              carDescription: Compact, 2/4 door, Automatic Transmission, Air Conditioning
              mileage: Unlimited
              pickUpDate: 2024-07-03 11:00
              pickupLocation: MIA Airport
              dropOffDate: 2024-07-04 11:00
              dropOffLocation: MIA Airport
    RedeemAirRoomInsurancePointsCash:
      value:
        bookingId: '1234567'
        createdDate: 2023-07-0718:54:00Z
        travelerProfileId: uniqueId1234
        points: 62073
        customerCurrency: USD
        lang: 1
        firstName: Checkout
        lastName: Customer
        country: US
        email: checkout@test.com
        phone: '3033121212'
        mobilePhone: '7204909090'
        addressLine1: Test address Line
        addressLine2: More address details
        city: Denver
        state: Colorado
        postalCode: '80249'
        metadata:
          payments:
          - type: Credit Card
            amount: 20
            currency: USD
            pointsAmount: 2000
          products:
          - id: 1
            type: AIR
            description: (JFK - CLT - SFO) - (SFO - JFK)
            pointsAmount: 48300
            shortfallCash: 0
            fullPrice: 483
            costOfGoods: 420
            tax: 17.7
            attributes:
              recordLocator: '12345'
              isRoundTrip: true
              travelerCounts:
                adults: 2
                children: 1
                infantsInSeat: 1
                infantsInLap: 0
              legs:
              - departureAirportCode: JFK
                departureDate: 2023-09-18 05:30
                arrivalAirportCode: SFO
                arrivalDate: 2023-09-18 11:45
                flightNumbers:
                - '1111'
                - '4567'
                airlineCodes:
                - AA
                layoverAirportCodes:
                - CLT
              - departureAirportCode: SFO
                departureDate: 2023-09-21 12:30
                arrivalAirportCode: JFK
                arrivalDate: 2023-09-21 17:45
                flightNumbers:
                - '555'
                airlineCodes:
                - AA
                layoverAirportCodes: []
          - id: 2
            type: ROOM
            description: Doubletree Hotel San Francisco Airport
            pointsAmount: 12000
            shortfallCash: 0
            fullPrice: 120
            costOfGoods: 104.34
            tax: 4.39
            attributes:
              hotelName: Doubletree Hotel San Francisco Airport
              hotelCity: BURLINGAME
              hotelCountry: US
              roomDescription: Room description
              checkIn: 2023-09-18 10:30
              checkOut: 2023-09-21 10:30
              nights: 2
              roomType: room_type
              occupantsCount: 1
          - id: 3
            type: INSURANCE
            description: Cancel for any reason.
            pointsAmount: 1773
            fullPrice: 27.73
            costOfGoods: 27.73
            tax: 0
            shortfallCash: 20
            attributes:
              contractName: Base Package
              startDate: 2023-09-18 00:00
              endDate: 2023-09-21 00:00
  schemas:
    Redeem:
      type: object
      format: json
      required:
      - bookingId
      - createdDate
      - travelerProfileId
      - points
      - customerCurrency
      - lang
      - firstName
      - lastName
      - country
      - email
      - phone
      - addressLine1
      - city
      - postalCode
      - metadata
      properties:
        bookingId:
          type: string
          description: Switchfly unique identifier assigned to a specific reservation or booking to track and manage it
        createdDate:
          type: string
          format: yyyy-MM-dd'T'HH:mm:ssX
          description: Date when the booking reservation was created
        travelerProfileId:
          type: string
          description: Unique Identifier for User Profile
        points:
          type: number
          description: Available points for User Profile. It is acceptable for this field to be 0 if the transaction was fully paid in cash
        customerCurrency:
          type: string
          description: Currency used for the cash display in the customer shopping flow
        lang:
          type: number
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          description: "Number value which shares the language used in this booking, related to langId send on Profile Response or matches the default language configured on the system:\n\n     1 - English\n     2 - French\n     3 - Spanish\n     4 - LA_Spanish\n     5 - Chinese_Simplified\n     6 - Japanese\n     7 - BR_Portuguese\n     8 - Thai\n     9 - German\n"
        firstName:
          type: string
          description: First name of the Lead traveler
        lastName:
          type: string
          description: Last name of the Lead traveler
        country:
          type: string
          format: ISO 3166 Alpha 2
          description: Two digits country code
        email:
          type: string
          description: Last name of the Lead traveler
        phone:
          type: string
          description: phone of the Lead traveler
        mobilePhone:
          type: string
          description: Sent only if present (Optional)
        addressLine1:
          type: string
          description: addressLine1 of the Lead traveler
        addressLine2:
          type: string
          description: Sent only if customer added extra address line
        city:
          type: string
          description: Traveler profile city
        state:
          type: string
          description: State Name
        postalCode:
          type: string
          description: Postal Code
        emailSubscription:
          type: boolean
          description: Indicates if the customer has opted in to receive email communications
        metadata:
          type: object
          required:
          - payments
          - products
          properties:
            payments:
              type: array
              description: Will contain only cash payment information if the booking required a topUp payment
              required: null
              items:
                type: object
                required:
                - type
                - amount
                - currency
                - pointsAmount
                properties:
                  type:
                    type: string
                    description: Type of payment description, if any payment was made with non-points, this will say Credit Card
                  amount:
                    type: number
                    description: Cash amount paid
                  currency:
                    type: string
                    description: Currency in which the CC was charged for the amount (matches customerCurrency)
                  pointsAmount:
                    type: number
                    description: This value corresponds to the amount of missing points the customer covers with this credit card payment on a partial point redemption
            products:
              type: array
              items:
                type: object
                description: Will contain all components (segments) that this booking has.Product objects will contain point allocation (points used to cover for the cost), cost of goods and tax details along with product specific details for each type of product
                required:
                - id
                - type
                - description
                - pointsAmount
                - shortfallCash
                - fullPrice
                - costOfGoods
                - tax
                - attributes
                properties:
                  id:
                    type: string
                    description: Unique identifier assigned to Product being purchased in Switchfly ecosystem
                  type:
                    type: string
                    enum:
                    - AIR
                    - CAR
                    - ACTIVITY
                    - ROOM
                    - INSURANCE
                    - FEE
                    description: The product type represented for this product section.  There will be one product node per travel segment within the given booking.
                  description:
                    type: string
                    description: Description of product
                  pointsAmount:
                    type: number
                    description: Points price of component
                  shortfallCash:
                    type: number
                    description: Shows if any cash payment was required for the product e.g if product is paid with points + cash this will describe the cash used
                  fullPrice:
                    type: number
                    description: Total Cash price of component
                  costOfGoods:
                    type: number
                    description: Managed by config
                  tax:
                    type: number
                    description: Total tax collected for this specific product in the booking.
                  attributes:
                    description: Attributes vary depending on the type of product, different properties will be send for AIR, ROOM, ACTIVITY, CAR, INSURANCE and FEE
                    oneOf:
                    - type: object
                      title: AirProduct
                      required:
                      - recordLocator
                      - isRoundTrip
                      - legs
                      - travelerCounts
                      description: AIR
                      properties:
                        recordLocator:
                          type: string
                          description: Flight ticket record locator
                        isRoundTrip:
                          type: boolean
                          description: Describes if the air product is roundtrip, which is true first leg departure airport is equal to last leg arrival airport
                        travelerCounts:
                          type: object
                          required:
                          - adults
                          - children
                          - infantsInSeat
                          - infantsInLap
                          properties:
                            adults:
                              type: number
                              description: Number of adult passengers
                            children:
                              type: number
                              description: Number of child passengers
                            infantsInSeat:
                              type: number
                              description: Number of infant in seat passengers
                            infantsInLap:
                              type: number
                              description: Number of infant in lap passengers
                        legs:
                          type: array
                          items:
                            type: object
                            required:
                            - departureAirportCode
                            - departureDate
                            - arrivalAirportCode
                            - arrivalDate
                            - flightNumbers
                            - airlineCodes
                            properties:
                              departureAirportCode:
                                type: string
                                description: Contains the start airport code for the trip
                              departureDate:
                                type: string
                                format: yyyy-MM-dd HH:mm
                                description: Contains the start date of the trip
                              arrivalAirportCode:
                                type: string
                                description: Contains the arrival airport code of the trip
                              arrivalDate:
                                type: string
                                format: yyyy-MM-dd HH:mm
                                description: Contains the arrival date of this trip,
                              flightNumbers:
                                type: array
                                description: Contains all the flight numbers of the entire trip
                                items:
                                  type: string
                              airlineCodes:
                                type: array
                                description: Contains all the airlines codes involved in the trip
                                items:
                                  type: string
                              layoverAirportCodes:
                                type: array
                                description: Contains all the airport codes from stops in this trip
                                items:
                                  type: string
                    - type: object
                      title: RoomProduct
                      description: ROOM
                      required:
                      - hotelName
                      - hotelCity
                      - hotelCountry
                      - roomDescription
                      - checkIn
                      - checkOut
                      - nights
                      - roomType
                      - occupantsCount
                      properties:
                        hotelName:
                          type: string
                          description: Name of hotel
                        hotelCity:
                          type: string
                          description: City name where the hotel is located
                        hotelCountry:
                          type: string
                          description: Country of hotel location
                        roomDescription:
                          type: string
                          description: Description of room reservation
                        checkIn:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Hotel reservation check in time
                        checkOut:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Hotel reservation checkout time
                        nights:
                          type: number
                          description: Number of nights the hotel reservation has
                        roomType:
                          type: string
                          description: Room type description
                        occupantsCount:
                          type: string
                          description: Number of guests in room(s)
                    - type: object
                      title: ActivityProduct
                      required:
                      - activityName
                      - activityDescription
                      - scheduledDate
                      - airportCode
                      - tourDuration
                      description: ACTIVITY
                      properties:
                        activityName:
                          type: string
                          description: Name of activity
                        activityDescription:
                          type: string
                          description: Description of activity details
                        scheduledDate:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Activity event start date
                        airportCode:
                          type: string
                          description: Closest Airport code to activity location
                        tourDuration:
                          type: string
                          description: Description of activity duration
                    - type: object
                      title: CarProduct
                      required:
                      - companyName
                      - carDescription
                      - mileage
                      - pickUpDate
                      - pickUpLocation
                      - dropOffDate
                      - dropOffLocation
                      description: CAR
                      properties:
                        companyName:
                          type: string
                          description: Car rental company name
                        carDescription:
                          type: string
                          description: SIPP car description
                          example: Standard, SUV, Automatic Transmission, Air Conditioning
                        mileage:
                          type: string
                          description: Mileage included on rental
                        pickUpDate:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Pick up date
                        pickUpLocation:
                          type: string
                          description: Pick up location of car can be airport location or off airport
                        dropOffDate:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Drop of date
                        dropOffLocation:
                          type: string
                          description: Drop off location of car can be airport location or off airport
                    - type: object
                      title: InsuranceProduct
                      required:
                      - contractName
                      - startDate
                      - endDate
                      description: INSURANCE
                      properties:
                        contractName:
                          type: string
                          description: Insurance product name
                        startDate:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: Start date of insurance
                        endDate:
                          type: string
                          format: yyyy-MM-dd HH:mm
                          description: End date of insurance
                    - type: object
                      title: FeeProduct
                      required:
                      - contractName
                      - feeType
                      description: INSURANCE
                      properties:
                        contractName:
                          type: string
                          description: Fee product description
                        feeType:
                          type: string
                          description: Specifies the type of fee applied to the transaction or service
    RedemptionConfirmation:
      required:
      - redemptionConfirmationId
      type: object
      format: json
      properties:
        redemptionConfirmationId:
          type: string
          description: Redemption confirmation unique id, will be used on `/refund` API calls for cancellation
    TravelerProfile:
      type: object
      format: json
      required:
      - travelerProfileId
      - balancePoints
      - customerCurrency
      - langId
      - firstName
      - lastName
      - email
      - phone
      - address
      - companyCode
      properties:
        travelerProfileId:
          type: string
          description: Traveler profile unique id
        balancePoints:
          type: number
          description: Available points in customer account used to redeem products
        customerCurrency:
          type: string
          enum:
          - USD
          - AED
          - AUD
          - BBD
          - BRL
          - BSD
          - CAD
          - COP
          - CRC
          - DOP
          - EUR
          - GBP
          - GTQ
          - HNL
          - IDR
          - ILS
          - INR
          - JMD
          - JOD
          - JPY
          - MXN
          - MYR
          - NOK
          - NZD
          - PAB
          - PEN
          - PHP
          - PLN
          - SGD
          - THB
          - TTD
          - UYU
          - VND
          - XCD
          - ZAR
          description: ISO 4217 Customer desired shop currency in case of cash top up.
        langId:
          type: number
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          description: "Language id used to specify the preferred language for shopping flow.\n\n     1 - English\n     2 - French\n     3 - Spanish\n     4 - LA_Spanish\n     5 - Chinese_Simplified\n     6 - Japanese\n     7 - BR_Portuguese\n     8 - Thai\n     9 - German\n"
        title:
          type: string
          enum:
          - Mr
          - Mrs
          - Miss
          - Ms
          - Dr
          - Mstr
          - Rev
          - Mx
        firstName:
          type: string
          description: Traveler profile first name
        lastName:
          type: string
          description: Traveler profile last name
        email:
          type: string
          description: Traveler profile email address
        phone:
          type: string
          description: Traveler profile preferred phone number
        address:
          type: object
          required:
          - addressLine1
          - city
          - countryCode
          properties:
            addressLine1:
              type: string
              description: Traveler profile address line 1
            addressLine2:
              type: string
              description: Traveler profile address line 2
            city:
              type: string
              description: Traveler profile city
            countryCode:
              type: string
              example: US
              description: ISO 3166-1 alpha-2 (2 letter country code)
            state:
              type: string
              example:
              - CA
              - Hauts-de-Seine
              - Catalonia
              description: ISO 3166-2 state codes or Free text for province/department/prefecture/region
        companyCode:
          type: string
          description: This is a profile parameter that Switchfly uses to customize branding and enable company-specific portal reporting
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Uses token retrieved from OAuth 2 SSO token requests
    adminBearerAuth:
      type: http
      scheme: bearer
      description: Uses token retrieved from Machine to Machine OAuth 2 client credentials token request.
